@extends('layouts.app') 
@section('content')
<style>

</style>

<div class="container bg-light">
 <div class="terms-page">
        <h1>Terms & Conditions</h1>
    <h1>(1.) GENERAL</h1>
        <p><b>In terms of Information Technology statutes, this document is an
                electronic record. Being generated by a computer system it does
                not require any physical or digital signatures.<b></P>
        <p><b>In terms of Information Technology statutes, this document is an electronic record. Being generated by a computer system it does
                            not require any physical or digital signatures.<b></P>
        <p><b>In terms of Information Technology statutes, this document is an
                electronic record. Being generated by a computer system it does
                not require any physical or digital signatures.<b></P>
        <p><b>A) The website www.ksrdms.com (hereinafter referred to as
                ‘Website’), owned by KSR Services, having its registered office at
                VPO Banwala, Tehsil Dabwali, District Sirsa, – 125103, Haryana,
                India represented by its members, where such expression shall,
                unless repugnant to the context thereof, be deemed to include its
                respective legal heirs, representatives, administrators, permitted
                successors and assigns;<b></P>
        <p><b>B) For the purpose of these Terms of Service, along with any
                amendments to the same, and wherever the context so requires:<b></P>               
               <Ul style="list-style:none;">
                   <li>i.) “You” or “User” shall mean any natural or legal person who has
                        agreed to become a user of the Website by logging into the Website.
                        The Website also provides certain services without
                        registration/acceptance, and such provision of services does not
                        absolve You of this contractual relationship</li>
                   <li> ii.) “We”, “Us”, “Our”, ‘Company’ shall mean KSR Services,</li>
                   <li>iii.) “Agreement” shall mean and refer to this Terms of Service,
                        including any amendments that may be incorporated into it.</li>
                   <li>v. “Services” shall mean the services provided on the Website.</li>
                   <li>vi. “Third Party” shall mean and refer to any individual(s), company or
                            entity apart from the User and the Company.</li>
                   <li>vii. “SMS” shall mean short message service.</li>
                                                     
                </ul>
        <p><b> C) The headings of each section in this Agreement are only for the
                purpose of organizing the various provisions under this Agreement in
                an orderly manner. These headings shall not be used by either party
                to interpret the provisions contained under them in any manner.
                Further, the headings have no legal or contractual value.<b></P>
        <p><b> D) By using the Website, You accept and agree to be bound by this
                Agreement, the Privacy Policy, as well as rules, guidelines, policies,
                terms and conditions applicable to any service that is provided by the
                Website, that shall be deemed to be incorporated into this Agreement
                and shall be considered as part and parcel of this Agreement.<b></P>
        <p><b> E) Your use of Our Website is evidence that You have read and
                agreed to be contractually bound by these Agreement and Our
                Privacy Policy. Please read both carefully. The use of this Website by
                You is governed by this policy and any policy so mentioned by terms
                of reference.<b></P>
        <p><b>F) If You do not agree with any of these terms, please discontinue
                using the Website.<b></P>
        <p><b>G) We hold the sole right to modify the Agreement without prior
                permission from You or providing notice to You. The relationship
                creates on You a duty to periodically check the Agreement and stay
                updated on its requirements. If You continue to use the Website or
                avail any of its Services without registration following such change,
                this is deemed as consent by You to the so amended policies. Your
                continued use of the Website is conditioned upon Your compliance
                with the Agreement, including but not limited to compliance with the
                Agreement even after alterations, if any.<b></P>                                    
                                                                                     
                                       
                                                         
    </div>

        <div class="terms-page">
           <h1>(2.) ABOUT US AND HOW WEBSITE OPERATES</h1>
               <p><b>We are a technology based Company along with providing the
                    services of Dairy Management System. The Website gives a free trail
                    for Dairy Management System Users and if You are satisfied with the
                    trial version You can opt for Our subscription plans as per Your
                    requirements. If an User is not satisfied with Our services We shall
                    give You a refund within 48(Fourty Eight) hours calculated from the
                    time the User has submitted the request for the same.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(3.) REGISTRATION</h1>
               <p><b>The Users could be from any field. If a User wants to avail services of
                    the Website and use it, registration is mandatory. As part of the
                    registration, We collect basic information such as Your dairy name,
                    dairy code, email address, mobile number and address.<br><br>
                    Information collected about You is subject to the Privacy Policy of the
                    Company, which is incorporated in these Agreement by reference.
                    Users can invite their contacts on email providers and social networks
                    to use the Website. Users can share information of the Company on
                    the said Third Party platforms.<br><br>
                    Further, at any time during Your use of this Website, including but not
                    limited to the time of registration, You are solely responsible for
                    protecting the confidentiality of Your username and password, and
                    any activity under the account shall be deemed to have been done by
                    You. In the case that You provide Us with false and/or inaccurate
                    details or we have reason to believe that You have done so, We hold
                    the right to permanently suspend Your account. Upon the request of
                    the User the account will be deleted. Refunds can be claimed only by
                    registered Users.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(4.) SMS</h1>
           <h4>I. Length of SMS</h4>
               <p><b>Single message size constitutes maximum upto 140(one forty)
                    characters incase of a CDMA SMS &amp; 160(one sixty) characters incase
                    of GSM SMS including the header &amp; footer submitted to Company’s Network. 
                    Incase the message is larger than the aforementioned characters, single 
                    message shall means 134(one thirty four) characters in the case of CDMA 
                    SMS &amp; 153 (one fifty three) characters in the case of GSM SMS respectively.<b></P>
                    <br><br>
                <p><b> II.The SMS sent to your members are the responsibility of yours.
                        The company will not be responsible if a SMS contains any
                        wrong or suspicious information sent by your login.<b></P >
                                <br><br>
                <p><b> III. You will get free SMS as per the selection of your subscription
                        plan. The company will not be responsible if you consume the
                        quantity before the expiration time. The SMS may be credited in
                        your account as per the requirement and on paid basis. The rate
                        will be charged per SMS as then that time of SMS rates including
                        GST 18%.<b></P >


                            
        </div>
        
        <div class="terms-page">
           <h1>(5.)NATIONAL DO NOT CALL REGISTRY</h1>
               <p><b>Notwithstanding anything contained in these Terms, You hereby agree
                    and undertake to fully comply with the Telecom Unsolicited
                    Commercial Communications Regulations, 2007 (the “TRAI
                    Regulations”) and its amendments and Guidelines for Telemarketers,
                    issued by Department of Telecommunications (“DOT Guidelines”) and
                    such other orders and directives issued by TRAI/ DOT from time to
                    time in this regard and also undertake NOT to send, under any
                    circumstances, any promotional messages using the Services, auto
                    dialers USSD messages, WAP messages or in any other manner to
                    any Customer, who is listed in the National Do Not Call Registry
                    (NDNC). In case of non-compliance of DOT Guidelines, We shall have
                    the right to terminate your account. If You use the Company Services
                    for sending any international SMS message to a Customer, You shall
                    be solely liable to comply with any legislation/ guidelines similar to
                    TRAI Regulations and DOT Guidelines applicable in such Customers
                    country of residence.<b></P>
                                   
        </div>

        
        <div class="terms-page">
           <h1>(6.)COMMUNICATIONS</h1>
               <p><b>By using this Website, it is deemed that You have consented to
                    receiving telephonic calls, SMSs and/or emails from Us at any time
                    We deem fit. Such communications shall be sent to You on the
                    telephone number and/or email address provided by You for the use
                    of this Website which are subject to our Privacy Policy. These
                    communications include, but are not limited to contacting You through
                    information received from Third Parties. Such communications by Us
                    is for purposes that inter alia include clarification calls, marketing calls
                    and promotional calls. In case You wish to stop receiving notifications
                    from Us with regard to marketing and promotional calls/ with regard to
                    any communication received from Us, You may do so by sending an
                    email at support@ksrdms.com<b></P>
                                   
        </div>

        <div class="terms-page">
           <h1>(7.) CHARGES</h1>
               <p><b>The Website offers different plans to the User which would enable
                    them to have a better participation in the Website and to create a
                    brand exclusively for the User. The Company reserves the right to
                    amend the fee policy for use of the Website and the charges for any or
                    all Services rendered. In such an event, the User will be intimated of
                    the same when it attempts to access the Website, and the User shall
                    have the option of declining to avail the Services offered on the
                    Website. Any such change, if made, shall come into effect
                    immediately upon such change being notified to the User, unless
                    specified otherwise.<b></P>
                                   
        </div>

        
        <div class="terms-page">
           <h1>(8.) MODE OF PAYMENT</h1>
               <p><b>Domestic and international credit cards issued by banks and financial
                    institutions that are part of the Visa, Master Card &amp; Amex Card
                    networks;
                    Visa &amp; Master Card Debit cards;
                    Net banking/Direct Debit payments from select banks.
                    CCAvenue<br><br>
                    The Website uses Third Party payment gateway to handle financial
                    transactions on the Website. We are not responsible for these third
                    Party services. Such services depend on the respective Third Party
                    legal terms. The billing details such as the User’s name and billing
                    address, provided during payment should be up-to-date. Payment
                    information of Users using Our services on the Website is stored in a
                    basic encryption format on the respective payment gateway’s
                    database servers. This encrypted information can be decrypted to
                    reveal the original information. This information is provided to us by
                    the Third Party payment gateway services we use to provide online
                    payment functionality, and hence, may contain certain personal
                    information.<br><br>
                    We are not responsible for what information is sent to us and it’s
                    stored as it is sent to us via third Party and we cannot control the
                    information sent. However, storage of this information is necessary for
                    legalities and auditing as well as for verification and more. Currently,
                    the information stored that may be deemed personal to the User is
                    their first name, last name, mobile number, email id and their address
                    zip code. If you wish to dispute a payment regarding your account,
                    you may talk to our Support staff directly.<b></P>
                                   
        </div>

        
        <div class="terms-page">
           <h1>(9.) TAXES</h1>
               <p><b>The User takes full responsibility for payment of all taxes and fees that
                    are levied or arise in the course of use of the Website, including but
                    not limited to downloading content and availing its service partner’s
                    service.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(10.) Security</h1>
               <p><b>Transactions on the Website are secure and protected. Any
                    information entered by the User when transacting on the Website is
                    encrypted to protect the User against unintentional disclosure to third
                    parties. The User’s credit and debit card information is not received,
                    stored by or retained by the Company / Website in any manner.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(11.) TERM/TERMINATION</h1>
               <p><b>These Terms shall continue to form a valid and binding contract
                    between the Parties, and shall continue to be in full force and effect
                    until the User continues to access and use the Website.<br><br>
                    You may terminate Your use of the Service at any time by ceasing to
                    use the Service. We may terminate these Terms and close Your
                    account at any time without notice, if we cease to provide the
                    Services. We may suspend or terminate Your use of and access to
                    the Website at any time and for any reason, in Our sole discretion.
                    Such suspension or termination shall not limit Our right to take any
                    other action against You that We consider appropriate.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(12.) USER’S OBLIGATIONS</h1>
               <p><b>The User undertakes to fulfil the following obligations. Failure to
                    satisfy any of these obligations gives Us the right to permanently
                    suspend Your account and/or claim damages for any losses that
                    accrue to Us or additional costs that may be imposed on us.<br><br>
                    You hereby certify that You are at least 18years of age.
                    You agree to ensure the email address provided in Your account
                    registration is valid at all times and shall keep Your contact information
                    accurate and up-to-date.<br><br>
                    You agree to comply with all local laws and regulations governing the
                    downloading, installation and/or use of the Website, including, without
                    limitation to, any usage rules set forth in this Agreement.
                    You undertake not to:<br><br>
                    a) Cut, copy, distribute, modify, recreate, reverse engineer, distribute,
                    disseminate post, publish or create derivative works from, transfer, or
                    sell any information or software obtained from the Website. For the
                    removal of doubt, it is clarified that unlimited or wholesale
                    reproduction, copying of the content for commercial or non-
                    commercial purposes and unwarranted modification of data and
                    information within the content of the Website is not permitted. Should
                    You want to engage in one or more such actions, prior permission
                    from Us must be obtained;<br><br>
                    b) access (or attempt to access) the Website and/or the materials or
                    services by any means other than through the interface that is
                    provided by the Website . The use of deep-link, robot, spider or other
                    automatic device, program, algorithm or methodology, or any similar
                    or equivalent manual process, to access, acquire, copy or monitor any
                    portion of the Website or Content, or in any way reproduce or
                    circumvent the navigational structure or presentation of the Website or
                    , materials or any Content, to obtain or attempt to obtain any
                    materials, documents or information through any means not
                    specifically made available through the Website is prohibited. You
                    acknowledge and agree that by accessing or using the Website
                    Services, You may be exposed to content from other Users or Third
                    Parties that You may consider offensive, indecent or otherwise
                    objectionable. We disclaim all liabilities arising in relation to such
                    offensive content on the Website. Further, You may report such
                    offensive content;<br><br>
                    c) use the Website or in any manner that may impair, overburden,
                    damage, disable or otherwise compromise (i) Company’s
                    Services; (ii) any other party’s use and enjoyment of company’s
                    Services; or (iii) the services and products of any Third Party
                    (including, without limitation to, the Authorized Device);
                    <br><br>
                    d) use the Services or materials for any unlawful purposes or to
                    conduct any unlawful activity, including, but not limited to, fraud,
                    embezzlement, money laundering or identity theft;<br><br>
                    e) abuse, harass, threaten, defame, disillusion, erode, abrogate,
                    demean or otherwise violate the legal rights of others;<br><br>
                    f) engage in any activity that interferes with or disrupts access to the
                    Website or the Services (or the servers and networks which are
                    connected to the );<br><br>
                    g) upload or distribute files that contain viruses, corrupted files, or any
                    other similar software or programs that may damage the operation of
                    the Website or another’s mobile phone;
                    <br><br>
                    h) download any file posted on the Website that You know, or
                    reasonably should know, cannot be legally distributed in such manner;
                    <br><br>
                    i) probe, scan or test the vulnerability of the Website or any connected
                    network , nor breach the security or authentication measures on the
                    Website. You may not reverse look-up, trace or seek to trace any
                    information on any other user, of or visitor to, the Website , or exploit
                    the Service or information made available or offered by or through the
                    Website, in any way whether or not the purpose is to reveal any
                    information, including but not limited to personal identification
                    information, other than Your own information, as provided for by the<br><br>
                    j) disrupt or interfere with the security of, or otherwise cause harm to,
                    the Website, systems resources, servers or networks connected to or
                    accessible through the Website or any affiliated or linked s;<br><br>
                    k) use the Website or any material or Content for any purpose that is
                    unlawful or prohibited by these Agreement, or to solicit the
                    performance of any illegal activity or other activity which infringes the
                    rights of this Website or other Third Parties;<br><br>
                    l) violate any applicable laws or regulations for the time being in force
                    within or outside Your home country;<br><br>
                    m) violate any code of conduct or other guidelines, which may be
                    applicable for or to any particular Service;<br><br>
                    n) Publish, post, disseminate, any information which is grossly
                    harmful, harassing, blasphemous, defamatory, obscene,
                    pornographic, paedophilic, libellous, invasive of another’s privacy,
                    hateful, or racially, ethnically objectionable, disparaging, relating or
                    encouraging money laundering or gambling, or otherwise unlawful in
                    any manner whatever; or unlawfully threatening or unlawfully
                    harassing including but not limited to “indecent representation of
                    women” within the meaning of the Indecent Representation of Women
                    (Prohibition) Act, 1986.<br><br>
                    o) threaten the unity, integrity, defence, security or sovereignty of Your
                    home country, friendly relations with foreign states, or public order or
                    causes incitement to the commission of any cognizable offence or
                    prevents investigation of any offence or is insulting any other nation;<br><br>
                    p) disseminate information through the Website that is false,
                    inaccurate or misleading, or violate any applicable laws or regulations
                    for the time being in force in or outside Your home country.
                                        <b></P>
                                   
        </div>

        
        <div class="terms-page">
           <h1>(13.) COPYRIGHT</h1>
               <p><b>All information, content, services and software displayed on,
                    transmitted through, or used in connection with the Website, including
                    for example news articles, reviews, directories, guides, text,
                    photographs, images, illustrations, audio clips, video, html, source and
                    object code, trademarks, logos, and the like (collectively and
                    hereinafter referred to as the “Content“), as well as its selection and
                    arrangement, is owned by Us. You may use the Content only through
                    the Website, and solely for Your personal, non-commercial use.
                    You may not, republish any portion of the Content on any Internet,
                    Intranet or extranet site or incorporate the Content in any database,
                    compilation, archive or cache. You may not distribute any Content to
                    others, whether or not for payment or other consideration, and You
                    may not modify, copy, frame, cache, reproduce, sell, publish, transmit,
                    display or otherwise use any portion of the Content. You may not
                    scrape or otherwise copy our Content without permission. You agree
                    not to decompile, reverse engineer or disassemble any software or
                    other products or processes accessible through the Website, not to
                    insert any code or product or manipulate the content of the Website in
                    any way that affects the user’s experience, and not to use any data
                    mining, data gathering or extraction method.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(14.) COPYRIGHT COMPLAINTS</h1>
               <p><b>.We respect the intellectual property of others. If You believe Your
                        work has been copied in a way that constitutes copyright infringement
                        or are aware of any infringing material on the Website, please contact
                        Us at support@ksrdms.com Information and Content provided by the User 
                        by providing information to, communicating with, and/or placing material 
                        on, the Website,including for example but not limited to, communication 
                        during any registration, You represent and warrant:<br><br>
                        You own or otherwise have all necessary rights to the content You
                        provide and the rights to use it as provided in this Agreement;
                        all information You provide is true, accurate, current and complete,
                        and does not violate these Agreement; and
                        the information and Content shall not cause injury to any person or
                        entity. Using a name other than Your own legal name is prohibited.
                        You authorize us to share the information across all our affiliated
                        Websites, to include the information in a searchable format accessible
                        by users of the Website, and to use Your name and any other
                        information in connection with its use of the material You provide. You
                        also grant the right to use any material, information, contained in any
                        communication You send to us for any purpose whatsoever, including
                        but not limited to developing, manufacturing and marketing products
                        using such information. All rights in this paragraph are granted without
                        the need for additional compensation of any sort to You.<b></P>
                                   
        </div>
        
                <div class="terms-page">
                   <h1>(15.) AMENDMENT</h1>
                        <p><b>We may modify, replace, refuse access to, suspend or discontinue the
                        Services, partially or entirely, or add, change and modify prices for all
                        or part of the Services for You or for all Users at any time and in Our
                        sole discretion. These changes shall become effective upon providing
                        a notice of the same to You via email/ the home screen of the
                        Website. We further reserve the right to withhold, remove and or
                        discard any content available as part of Your account, with or without
                        notice, if deemed by Us to be contrary to this Agreement.
                        The Website has no obligation to provide You with a copy of the
                        information You or any other User provides on the Website or that the
                        Website has accessed.<br><br>
                        Further, We reserve the right, in Our sole discretion, to modify or
                        replace any part of this Agreement at any time, effective upon the date
                        of giving Users notice of the same. Notice shall be provided of such
                        change via email to the Users and/ or by posting a notice on the home
                        screen of the Website.<br><br>
                        You and We both understand that there may be instances of difficulty
                        in accessing or receiving email communication. We are not
                        responsible if any email notice gets caught by Your SPAM folder, or if
                        You do not see the email, or if You have given us an incorrect email id
                        or if for any other reason You do not receive the email notice.
                        Therefore, we encourage You to frequently open the Website to
                        monitor any changes. Your continued use of or access to the Services
                        following the posting of any changes to this Agreement constitutes
                        acceptance of those changes. We may also, in the future, offer new
                        Services and/ or features through the Website. Such new features
                        and/ or services shall be subject to the terms and conditions of this
                        Agreement.<b></P>
                                           
                </div>
                
        <div class="terms-page">
           <h1>(16.) INDEMNIFICATION</h1>
               <p><b>.a) You agree to indemnify, hold harmless, and defend Us from and
                against any and all liability, loss, claim, damages, expense, or costs
                (including but not limited to attorneys’ fees), incurred by or made Us in
                connection with any claim arising from or related to :<br><br>
                Your use or any Third Party’s use via Your account of the Service
                provided by the Website and its Content;
                Your disclosure of information to any Third Party, either through the
                Website or otherwise. (Please refer to our Privacy Policy for more
                details in this regard);
                Any breach or violation of this Agreement, including any amendment,
                or of any statute or regulation by You, or any Third Party through Your
                account.<br><br>
                b) You agree to fully cooperate in indemnifying Us at Your expense.
                You also agree not to reach a settlement with any party without Our
                consent.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(17.) GEOGRAPHICAL EXTENT</h1>
               <p><b>The Website can be used worldwide. We make no representation that
                the content available through Our Website is appropriate or available
                for all countries. If You access or use the Website in any countries
                where the Website is prohibited, You are solely responsible for
                compliance with necessary laws and regulations for use of the
                Website.<b></P>
                                   
        </div>
        
        <div class="terms-page">
           <h1>(18.) DISCLAIMER OF LIABILITY AND WARRANTIES</h1>
           <h4>(20)PRIVACY</h4>
               <p><b>We encourage You to read the Privacy Policy, and to use the
                information it contains to make informed decisions regarding Your
                personal information. Please also note that certain information,
                statements, data and content (such as but not limited to information
                related to Your sign-up) which You provide on the Website are likely to
                reveal Your information about You. You acknowledge and agree that
                Your submission of such information is voluntary on Your part.
                Further, You acknowledge, consent and agree that We may access,
                preserve, and disclose information You provide to Us at any stage
                during Your use of the Website. Disclosures of information to Third
                Parties are further addressed in Our Privacy Policy. The data collected
                from the Users as well as from the Service provider may be located in
                servers outside of India.<b></P>
                <h4>(21) NOTICES</h4>
                <p><b>We encourage You to read the Privacy Policy, and to use the
                information it contains to make informed decisions regarding Your
                personal information. Please also note that certain information,
                statements, data and content (such as but not limited to information
                related to Your sign-up) which You provide on the Website are likely to
                reveal Your information about You. You acknowledge and agree that
                Your submission of such information is voluntary on Your part.
                Further, You acknowledge, consent and agree that We may access,
                preserve, and disclose information You provide to Us at any stage
                during Your use of the Website. Disclosures of information to Third
                Parties are further addressed in Our Privacy Policy. The data collected
                from the Users as well as from the Service provider may be located in
                servers outside of India.<b></P>
                <h4>(22) MISCELLANEOUS PROVISIONS:</h4>
                <p><b>Entire Agreement: This Agreement is the complete and exclusive
                statement of the agreements between You and Us with respect to the
                subject matter hereof and supersedes all other communications or
                representations or agreements (whether oral, written or otherwise)
                relating thereto.<br><br>
                Waiver: The failure of either party at any time to require performance
                of any provision of this Agreement in no manner shall affect such
                party’s right at a later time to enforce the same. No waiver by either
                party of any breach of this Agreement, whether by conduct or
                otherwise, in any one or more instances, shall be deemed to be, or
                construed as, a further or continuing waiver of any other such breach,
                or a waiver of any other breach of this Agreement.<br><br>
                Severability: If any provision of this Agreement shall to any extent be
                held invalid, illegal or unenforceable, the validity, legality and
                enforceability of the remaining provisions of this Agreement shall in no
                way be affected or impaired thereby and each such provision of this
                Agreement shall be valid and enforceable to the fullest extent
                permitted by law. In such case, this Agreement shall be reformed to
                the minimum extent necessary to correct any invalidity, illegality or
                unenforceability, while preserving to the maximum extent the rights
                and commercial expectations of the parties hereto, as expressed
                herein.<br><br>
                Liability: The Company shall not be liable in any way for User Content,
                including, but not limited to, any errors or omissions contained therein,
                or any loss or damage of any kind incurred as a result of the use of
                any User Content posted, emailed, transmitted or otherwise made
                available via the Service or broadcast elsewhere.<br><br>

                <b></P>        
                                
                


                            
        </div>
</div>
<br>


@endsection